const STORAGE='daspas_clientes_v2';
let clientes=JSON.parse(localStorage.getItem(STORAGE)||'[]');const $=id=>document.getElementById(id);const fields=['nro_afiliado','sindicato','categoria','apellido','nombre','documento','direccion','localidad','cod_postal','provincia','telefono','correo_electronico','datos_adjuntos','notas'];
function guardar(){localStorage.setItem(STORAGE,JSON.stringify(clientes))}function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function render(){const q=$('buscar').value.trim().toLowerCase(),rows=clientes.filter(c=>Object.values(c).some(v=>String(v??'').toLowerCase().includes(q)));$('contador').textContent=`${rows.length} registros`;$('sinResultados').style.display=rows.length?'none':'block';$('tablaClientes').innerHTML=rows.map(c=>`<tr><td>${c.id}</td><td>${esc(c.nro_afiliado)}</td><td>${esc(c.apellido)}, ${esc(c.nombre)}</td><td>${esc(c.documento)}</td><td>${esc(c.sindicato)}</td><td>${esc(c.categoria)}</td><td>${esc(c.localidad)}</td><td>${esc(c.telefono)}</td><td><div class="actions"><button class="secondary" onclick="editar(${c.id})">Editar</button><button class="danger" onclick="eliminar(${c.id})">Eliminar</button></div></td></tr>`).join('')}
function nuevo(){$('formCliente').reset();$('id').value='';$('tituloFormulario').textContent='Nuevo cliente';$('archivoActual').textContent='';$('panelFormulario').classList.remove('hidden');window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}
function editar(id){const c=clientes.find(x=>x.id===id);if(!c)return;fields.forEach(k=>{const el=$(k);if(el&&k!=='datos_adjuntos')el.value=c[k]||''});$('id').value=id;$('tituloFormulario').textContent='Editar cliente';$('archivoActual').textContent=c.datos_adjuntos?`Archivo: ${c.datos_adjuntos}`:'';$('panelFormulario').classList.remove('hidden')}
function eliminar(id){if(confirm('¿Eliminar este cliente?')){clientes=clientes.filter(c=>c.id!==id);guardar();render()}}
$('formCliente').addEventListener('submit',e=>{e.preventDefault();const id=Number($('id').value)||Date.now(),actual=clientes.find(c=>c.id===id)||{},c={id};fields.forEach(k=>c[k]=k==='datos_adjuntos'?($('datos_adjuntos').files[0]?.name||actual.datos_adjuntos||''):$(`${k}`).value);const i=clientes.findIndex(x=>x.id===id);if(i>=0)clientes[i]=c;else clientes.push(c);guardar();render();$('panelFormulario').classList.add('hidden');alert('Cliente guardado correctamente.')});
$('buscar').addEventListener('input',render);$('btnNuevo').addEventListener('click',nuevo);$('btnCerrar').addEventListener('click',()=> $('panelFormulario').classList.add('hidden'));$('btnCancelar').addEventListener('click',()=> $('panelFormulario').classList.add('hidden'));
function mensaje(t,c=''){const e=$('mensajeImportacion');e.textContent=t;e.className=c}
$('btnImportar').addEventListener('click',()=>{const file=$('archivoExcel').files[0];if(!file){mensaje('Seleccione un archivo Excel.','error');return}const r=new FileReader();r.onload=e=>{try{const wb=XLSX.read(e.target.result,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],data=XLSX.utils.sheet_to_json(ws,{defval:''});const map={'Nro Afiliado':'nro_afiliado','Nro. Afiliado':'nro_afiliado','nro_afiliado':'nro_afiliado','Sindicato':'sindicato','Categoría':'categoria','categoria':'categoria','Apellido':'apellido','Nombre':'nombre','Documento':'documento','DNI':'documento','Dirección':'direccion','Localidad':'localidad','Cod. Postal':'cod_postal','Código Postal':'cod_postal','Provincia':'provincia','Teléfono':'telefono','Correo Electrónico':'correo_electronico','Datos Adjuntos':'datos_adjuntos','Notas':'notas'};let nuevos=0,actualizados=0;data.forEach(raw=>{const c={id:Date.now()+nuevos};Object.entries(raw).forEach(([k,v])=>{const f=map[k]||k.toLowerCase().replace(/\s+/g,'_');if(fields.includes(f))c[f]=String(v??'').trim()});if(!['Activo','Jubilado','Individual'].includes(c.categoria))c.categoria='Activo';const key=c.nro_afiliado||c.documento,i=clientes.findIndex(x=>key&&(x.nro_afiliado===key||x.documento===key));if(i>=0){c.id=clientes[i].id;clientes[i]={...clientes[i],...c};actualizados++}else{clientes.push(c);nuevos++}});guardar();render();mensaje(`Importación completada: ${nuevos} nuevos y ${actualizados} actualizados.`,'ok')}catch(err){mensaje('Error al importar: '+err.message,'error')}};r.readAsArrayBuffer(file)});
$('btnExportar').addEventListener('click',()=>{const ws=XLSX.utils.json_to_sheet(clientes),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Clientes');XLSX.writeFile(wb,'DASPAS_clientes.xlsx')});$('btnPlantilla').addEventListener('click',()=>{const ws=XLSX.utils.json_to_sheet([{nro_afiliado:'',sindicato:'',categoria:'Activo',apellido:'',nombre:'',documento:'',direccion:'',localidad:'',cod_postal:'',provincia:'',telefono:'',correo_electronico:'',datos_adjuntos:'',notas:''}]),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Clientes');XLSX.writeFile(wb,'DASPAS_plantilla_importacion.xlsx')});render();