const $=s=>document.querySelector(s), app=$('#app'); let me=null, current=null;
const fields=['nro_afiliado','sindicato','categoria','apellido','nombre','documento','direccion','localidad','cod_postal','provincia','telefono','correo_electronico','notas'];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function api(url,opt={}){const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Error');return d}
async function boot(){try{me=await api('/api/me');dashboard()}catch{login()}}
function login(){app.innerHTML=`<main class="login-page"><div class="login-box"><img src="logo-daspas.svg" class="login-logo"><h1>Iniciar sesión</h1><p>Gestión centralizada de afiliados</p><form id="login"><input id="email" type="email" placeholder="Usuario o email" required><input id="password" type="password" placeholder="Contraseña" required><button class="primary">Ingresar</button><small>Acceso seguro para usuarios autorizados</small></form></div></main>`;$('#login').onsubmit=async e=>{e.preventDefault();try{me=await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('#email').value,password:$('#password').value})});dashboard()}catch(x){alert(x.message)}}}
function shell(active,body){app.innerHTML=`<div class="layout"><aside><div class="sidebrand"><img src="logo-daspas.svg"></div><nav><button class="${active==='inicio'?'active':''}" onclick="dashboard()">⌂ <span>Panel principal</span></button><button class="${active==='clientes'?'active':''}" onclick="clientes()">♙ <span>Clientes</span></button><button onclick="importar()">⇧ <span>Importar Excel</span></button><button onclick="documentos()">▣ <span>Documentación</span></button><button onclick="historial()">◷ <span>Historial</span></button>${me.rol==='admin'?'<button onclick="usuarios()">♙ <span>Usuarios</span></button>':''}</nav><button class="logout" onclick="logout()">↪ Cerrar sesión</button></aside><section class="main"><header><div><span class="muted">DASPAS · Broker de Seguros</span><h1>${active==='inicio'?'Panel principal':active[0].toUpperCase()+active.slice(1)}</h1></div><div class="user"><b>${esc(me.nombre)}</b><small>${esc(me.rol)}</small></div></header>${body}</section></div>`}
async function dashboard(){const d=await api('/api/dashboard');shell('inicio',`<div class="stats"><div><span>Clientes</span><b>${d.total}</b></div><div><span>Activos</span><b>${d.activos}</b></div><div><span>Jubilados</span><b>${d.jubilados}</b></div><div><span>Individuales</span><b>${d.individuales}</b></div><div><span>Documentos</span><b>${d.documentos}</b></div></div><div class="grid2"><section class="panel"><h2>Acciones rápidas</h2><div class="quick"><button onclick="nuevo()">＋ Nuevo cliente</button><button onclick="importar()">⇧ Importar Excel</button><button onclick="clientes()">⌕ Buscar clientes</button></div></section><section class="panel"><h2>Estado del sistema</h2><p>Base de datos central conectada.</p><p class="ok">● Servicio operativo</p><p class="muted">Usuario: ${esc(me.email)}</p></section></div>`)}
async function clientes(){shell('clientes',`<section class="panel"><div class="toolbar"><input id="search" placeholder="Buscar apellido, nombre, DNI, afiliado, sindicato..."><button class="primary" onclick="nuevo()">＋ Nuevo cliente</button></div><div id="table">Cargando...</div></section>`);const load=async()=>{const rows=await api('/api/clientes?search='+encodeURIComponent($('#search').value));$('#table').innerHTML=`<table><thead><tr><th>Afiliado</th><th>Apellido y nombre</th><th>Documento</th><th>Sindicato</th><th>Categoría</th><th>Localidad</th><th></th></tr></thead><tbody>${rows.map(c=>`<tr><td>${esc(c.nro_afiliado)}</td><td><b>${esc(c.apellido)}, ${esc(c.nombre)}</b></td><td>${esc(c.documento)}</td><td>${esc(c.sindicato)}</td><td><span class="tag">${esc(c.categoria)}</span></td><td>${esc(c.localidad)}</td><td><button class="link" onclick="ficha(${c.id})">Ver ficha</button></td></tr>`).join('')}</tbody></table>`};$('#search').oninput=load;load()}
function formHTML(c={}){return `<form id="clientForm" class="formgrid">${fields.map(f=>f==='categoria'?`<label>Categoría<select id="f_${f}"><option ${c[f]==='Activo'?'selected':''}>Activo</option><option ${c[f]==='Jubilado'?'selected':''}>Jubilado</option><option ${c[f]==='Individual'?'selected':''}>Individual</option></select></label>`:`<label>${f.replaceAll('_',' ')}<input id="f_${f}" value="${esc(c[f]||'')}" ${['nro_afiliado','sindicato','apellido','nombre'].includes(f)?'required':''}></label>`).join('')}<div class="wide"><button class="primary">Guardar cliente</button></div></form>`}
function nuevo(){current=null;shell('clientes',`<section class="panel"><div class="panelhead"><h2>Nuevo afiliado</h2><button onclick="clientes()">Volver</button></div>${formHTML()}</section>`);bindForm()}
function bindForm(){ $('#clientForm').onsubmit=async e=>{e.preventDefault();const b={};fields.forEach(f=>b[f]=$('#f_'+f).value);try{const d=await api(current?'/api/clientes/'+current.id:'/api/clientes',{method:current?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});ficha(d.id)}catch(x){alert(x.message)}}}
async function ficha(id){current=await api('/api/clientes/'+id);shell('clientes',`<section class="panel"><div class="panelhead"><div><span class="muted">Ficha del afiliado</span><h2>${esc(current.apellido)}, ${esc(current.nombre)}</h2></div><div><button onclick="editar()">Editar</button> ${me.rol==='admin'?'<button class="danger" onclick="borrar()">Eliminar</button>':''}</div></div><div class="profile"><div class="avatar">${esc((current.nombre||'?')[0])}</div><div><b>Nro. Afiliado</b><p>${esc(current.nro_afiliado)}</p><b>Documento</b><p>${esc(current.documento)}</p><b>Categoría</b><p><span class="tag">${esc(current.categoria)}</span></p></div><div><b>Dirección</b><p>${esc(current.direccion)}</p><b>Localidad / Provincia</b><p>${esc(current.localidad)} · ${esc(current.provincia)}</p><b>Teléfono</b><p>${esc(current.telefono)}</p><b>Email</b><p>${esc(current.correo_electronico)}</p></div></div><div class="tabs"><button onclick="ficha(${id})">Datos personales</button><button onclick="docsFicha(${id})">Documentación (${current.documentos.length})</button><button onclick="histFicha(${id})">Historial (${current.historial.length})</button></div></section>`)}
function editar(){shell('clientes',`<section class="panel"><div class="panelhead"><h2>Editar afiliado</h2><button onclick="ficha(${current.id})">Volver</button></div>${formHTML(current)}</section>`);bindForm()}
async function borrar(){if(confirm('¿Eliminar definitivamente este afiliado?')){await api('/api/clientes/'+current.id,{method:'DELETE'});clientes()}}
async function docsFicha(id){current=await api('/api/clientes/'+id);shell('clientes',`<section class="panel"><div class="panelhead"><h2>Documentación adjunta</h2><button onclick="ficha(${id})">Volver a ficha</button></div><form id="up" class="upload"><input type="file" id="doc" required><button class="primary">Subir documento</button></form><table><thead><tr><th>Archivo</th><th>Tipo</th><th>Fecha</th><th></th></tr></thead><tbody>${current.documentos.map(d=>`<tr><td>${esc(d.nombre)}</td><td>${esc(d.tipo)}</td><td>${new Date(d.creado_en).toLocaleString()}</td><td><a class="link" href="/api/documentos/${d.id}/download">Descargar</a></td></tr>`).join('')}</tbody></table></section>`);$('#up').onsubmit=async e=>{e.preventDefault();const fd=new FormData();fd.append('archivo',$('#doc').files[0]);await api('/api/clientes/'+id+'/documentos',{method:'POST',body:fd});docsFicha(id)}}
function histFicha(id){shell('clientes',`<section class="panel"><div class="panelhead"><h2>Historial del afiliado</h2><button onclick="ficha(${id})">Volver a ficha</button></div><div id="hist">Cargando...</div></section>`);api('/api/clientes/'+id).then(c=>{$('#hist').innerHTML='<table><thead><tr><th>Fecha</th><th>Usuario</th><th>Acción</th><th>Detalle</th></tr></thead><tbody>'+c.historial.map(h=>`<tr><td>${new Date(h.creado_en).toLocaleString()}</td><td>${esc(h.usuario||'')}</td><td>${esc(h.accion)}</td><td>${esc(h.detalle)}</td></tr>`).join('')+'</tbody></table>'})}
function importar(){shell('importar',`<section class="panel"><h2>Importar datos desde Excel</h2><p class="muted">Columnas reconocidas: Nro Afiliado, Sindicato, Categoría, Apellido, Nombre, Documento/DNI, Dirección, Localidad, Código Postal, Provincia, Teléfono, Correo Electrónico y Notas.</p><form id="imp" class="importbox"><input id="excel" type="file" accept=".xlsx,.xls,.csv" required><button class="primary">Importar Excel</button></form><div id="result"></div></section>`);$('#imp').onsubmit=async e=>{e.preventDefault();const fd=new FormData();fd.append('archivo',$('#excel').files[0]);try{const r=await api('/api/importar',{method:'POST',body:fd});$('#result').innerHTML=`<div class="notice ok">Importación finalizada: ${r.nuevos} nuevos · ${r.actualizados} actualizados · ${r.errores} errores.</div>`}catch(x){$('#result').innerHTML=`<div class="notice error">${esc(x.message)}</div>`}}}
function documentos(){shell('documentos',`<section class="panel"><h2>Documentación</h2><p>Los documentos se gestionan desde la ficha de cada afiliado, con usuario y fecha registrados.</p><button class="primary" onclick="clientes()">Ir a clientes</button></section>`)}
async function historial(){shell('historial',`<section class="panel"><h2>Historial</h2><p class="muted">El historial completo se consulta desde cada ficha de afiliado.</p><button class="primary" onclick="clientes()">Buscar afiliado</button></section>`)}
function usuarios(){shell('usuarios',`<section class="panel"><h2>Usuarios</h2><p>La administración de usuarios queda reservada al rol administrador.</p><p class="muted">Usuario actual: ${esc(me.email)}</p></section>`)}
async function logout(){await api('/api/logout',{method:'POST'});me=null;login()} boot();
