require('dotenv').config();
const express=require('express'),path=require('path'),fs=require('fs'),jwt=require('jsonwebtoken'),bcrypt=require('bcryptjs'),cookieParser=require('cookie-parser'),multer=require('multer'),xlsx=require('xlsx');
const {Pool}=require('pg');
const app=express(); const port=process.env.PORT||3000; const pool=new Pool({connectionString:process.env.DATABASE_URL});
const uploadDir=path.resolve(process.env.UPLOAD_DIR||'./uploads'); fs.mkdirSync(uploadDir,{recursive:true});
const upload=multer({dest:uploadDir,limits:{fileSize:15*1024*1024}});
app.use(express.json({limit:'2mb'})); app.use(cookieParser()); app.use(express.static(__dirname));
function auth(req,res,next){const token=req.cookies.daspas_token||String(req.headers.authorization||'').replace('Bearer ',''); try{req.user=jwt.verify(token,process.env.JWT_SECRET);next()}catch{return res.status(401).json({error:'Sesión no válida'})}}
function admin(req,res,next){if(req.user.rol!=='admin')return res.status(403).json({error:'Permisos insuficientes'});next()}
async function log(client,usuarioId,clienteId,accion,detalle){await client.query('INSERT INTO historial(usuario_id,cliente_id,accion,detalle) VALUES($1,$2,$3,$4)',[usuarioId,clienteId,accion,detalle||''])}
app.post('/api/login',async(req,res)=>{try{const {email,password}=req.body;const r=await pool.query('SELECT * FROM usuarios WHERE lower(email)=lower($1) AND activo=true',[email]);if(!r.rowCount||!await bcrypt.compare(password,r.rows[0].password_hash))return res.status(401).json({error:'Usuario o contraseña incorrectos'});const u=r.rows[0];const token=jwt.sign({id:u.id,nombre:u.nombre,email:u.email,rol:u.rol},process.env.JWT_SECRET,{expiresIn:'8h'});res.cookie('daspas_token',token,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:8*60*60*1000});res.json({id:u.id,nombre:u.nombre,email:u.email,rol:u.rol})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/logout',(req,res)=>{res.clearCookie('daspas_token');res.json({ok:true})});
app.get('/api/me',auth,(req,res)=>res.json(req.user));
app.get('/api/dashboard',auth,async(req,res)=>{const q=await pool.query("SELECT COUNT(*)::int total, COUNT(*) FILTER(WHERE categoria='Activo')::int activos, COUNT(*) FILTER(WHERE categoria='Jubilado')::int jubilados, COUNT(*) FILTER(WHERE categoria='Individual')::int individuales FROM clientes");const d=await pool.query('SELECT COUNT(*)::int total FROM documentos');res.json({...q.rows[0],documentos:d.rows[0].total})});
app.get('/api/clientes',auth,async(req,res)=>{const s=String(req.query.search||'').trim();const q=`SELECT * FROM clientes WHERE ($1='' OR nro_afiliado ILIKE '%'||$1||'%' OR documento ILIKE '%'||$1||'%' OR apellido ILIKE '%'||$1||'%' OR nombre ILIKE '%'||$1||'%' OR sindicato ILIKE '%'||$1||'%' OR localidad ILIKE '%'||$1||'%') ORDER BY apellido,nombre LIMIT 500`;res.json((await pool.query(q,[s])).rows)});
app.get('/api/clientes/:id',auth,async(req,res)=>{const c=await pool.query('SELECT * FROM clientes WHERE id=$1',[req.params.id]);if(!c.rowCount)return res.status(404).json({error:'Cliente no encontrado'});const docs=await pool.query('SELECT id,nombre,tipo,tamano,creado_en FROM documentos WHERE cliente_id=$1 ORDER BY creado_en DESC',[req.params.id]);const hist=await pool.query('SELECT h.*,u.nombre usuario FROM historial h LEFT JOIN usuarios u ON u.id=h.usuario_id WHERE cliente_id=$1 ORDER BY h.creado_en DESC LIMIT 100',[req.params.id]);res.json({...c.rows[0],documentos:docs.rows,historial:hist.rows})});
const fields=['nro_afiliado','sindicato','categoria','apellido','nombre','documento','direccion','localidad','cod_postal','provincia','telefono','correo_electronico','notas'];
app.post('/api/clientes',auth,async(req,res)=>{const b=req.body;const client=await pool.connect();try{await client.query('BEGIN');const q=`INSERT INTO clientes(${fields.join(',')},creado_por) VALUES(${fields.map((_,i)=>'$'+(i+1)).join(',')},$${fields.length+1}) RETURNING *`;const r=await client.query(q,[...fields.map(f=>b[f]||''),req.user.id]);await log(client,req.user.id,r.rows[0].id,'Alta','Se creó el cliente');await client.query('COMMIT');res.status(201).json(r.rows[0])}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}});
app.put('/api/clientes/:id',auth,async(req,res)=>{const b=req.body;const client=await pool.connect();try{await client.query('BEGIN');const set=fields.map((f,i)=>`${f}=$${i+1}`).join(',');const r=await client.query(`UPDATE clientes SET ${set},actualizado_en=NOW() WHERE id=$${fields.length+1} RETURNING *`,[...fields.map(f=>b[f]||''),req.params.id]);if(!r.rowCount)throw Error('Cliente no encontrado');await log(client,req.user.id,req.params.id,'Edición','Se actualizaron los datos');await client.query('COMMIT');res.json(r.rows[0])}catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message})}finally{client.release()}});
app.delete('/api/clientes/:id',auth,admin,async(req,res)=>{await pool.query('DELETE FROM clientes WHERE id=$1',[req.params.id]);res.json({ok:true})});
app.post('/api/clientes/:id/documentos',auth,upload.single('archivo'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'Falta el archivo'});await pool.query('INSERT INTO documentos(cliente_id,nombre,ruta,tipo,tamano,usuario_id) VALUES($1,$2,$3,$4,$5,$6)',[req.params.id,req.file.originalname,req.file.path,req.file.mimetype,req.file.size,req.user.id]);await pool.query('INSERT INTO historial(usuario_id,cliente_id,accion,detalle) VALUES($1,$2,$3,$4)',[req.user.id,req.params.id,'Documentación','Se agregó '+req.file.originalname]);res.json({ok:true})});
app.get('/api/documentos/:id/download',auth,async(req,res)=>{const r=await pool.query('SELECT * FROM documentos WHERE id=$1',[req.params.id]);if(!r.rowCount)return res.sendStatus(404);res.download(r.rows[0].ruta,r.rows[0].nombre)});
app.post('/api/importar',auth,upload.single('archivo'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'Falta el Excel'});try{const wb=xlsx.readFile(req.file.path);const rows=xlsx.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});const aliases={nro_afiliado:['nro afiliado','n° afiliado','nº afiliado','afiliado'],sindicato:['sindicato'],categoria:['categoria','categoría'],apellido:['apellido'],nombre:['nombre'],documento:['documento','dni'],direccion:['direccion','dirección'],localidad:['localidad'],cod_postal:['cod postal','codigo postal','código postal'],provincia:['provincia'],telefono:['telefono','teléfono'],correo_electronico:['correo electronico','correo electrónico','email'],notas:['notas']};const norm=s=>String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();let nuevos=0,actualizados=0,errores=0;for(const row of rows){const r={};const keys=Object.keys(row);for(const f of fields){const k=keys.find(x=>aliases[f]?.includes(norm(x))||norm(x)===norm(f));r[f]=k?String(row[k]??'').trim():''}if(!r.nro_afiliado||!r.apellido||!r.nombre){errores++;continue}const c=await pool.connect();try{await c.query('BEGIN');const old=await c.query('SELECT id FROM clientes WHERE nro_afiliado=$1',[r.nro_afiliado]);if(old.rowCount){await c.query(`UPDATE clientes SET ${fields.map((f,i)=>`${f}=$${i+1}`).join(',')},actualizado_en=NOW() WHERE id=$${fields.length+1}`,[...fields.map(f=>r[f]),old.rows[0].id]);actualizados++}else{const ins=await c.query(`INSERT INTO clientes(${fields.join(',')},creado_por) VALUES(${fields.map((_,i)=>'$'+(i+1)).join(',')},$${fields.length+1}) RETURNING id`,[...fields.map(f=>r[f]),req.user.id]);await log(c,req.user.id,ins.rows[0].id,'Importación','Alta desde Excel');nuevos++}await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');errores++}finally{c.release()}}await pool.query('INSERT INTO importaciones(usuario_id,archivo,total,nuevos,actualizados,errores) VALUES($1,$2,$3,$4,$5,$6)',[req.user.id,req.file.originalname,rows.length,nuevos,actualizados,errores]);res.json({total:rows.length,nuevos,actualizados,errores})}catch(e){res.status(400).json({error:'No se pudo leer el Excel: '+e.message})}finally{fs.unlink(req.file.path,()=>{})}});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));
app.listen(port,()=>console.log('DASPAS en http://localhost:'+port));
